### ISSUE TITLE
Symfony 3.0 composer compatibility

### ISSUE THREAD

**Issue by enricoghdn** [gfreeau/GfreeauGetJWTBundle#19]
So, it seems composer won't let you install this bundle if your Symfony application is based on Symfony 3.0 since this bundle requires Symfony up to v2.8.4. Could you update to fix?

**Comment by gfreeau** [comment]
Try the 2.0 version.

```
composer require gfreeau/get-jwt-bundle:2.0.x-dev
```

I'll need to tag this as an official release.

**Comment by enricoghdn** [comment]
Worked great! Had to update jwt-authentication-bundle to `2.0.x-dev` as well but composer has successfully installed both bundles. Thank you! :)
