### ISSUE TITLE
Symfony 3.0 compatibility

### ISSUE THREAD

**Issue by glannez** [gfreeau/GfreeauGetJWTBundle#20]
Hi, i'm trying to upgrade my project to symfony 3.0.
I've got the following deprecated warning :

> Using paths to find deeper items in Symfony\Component\HttpFoundation\ParameterBag::get is deprecated since version 2.8 and will be removed in 3.0. Filter the returned value in your own code instead: 

Calls to the get() function on ParameterBag can not be deep anymore.

Any suggestions to remove this deprecated call or maybe this is a pending changes ?

**Comment by gfreeau** [comment]
Pull requests are welcome. We can merge this into a release for symfony 3.

**Comment by mikelohmann** [comment]
Is it really necessary to have a deep = true in 
`$request->request->get($this->options['username_parameter'], null, true)`
the ->get calls?

If I follow the instructions there is no way to set username / password parameters in a deeper structure, is it?
