### ISSUE TITLE
Status 500 on invalid username

### ISSUE THREAD

**Issue by akomm** [gfreeau/GfreeauGetJWTBundle#27]
[trim in Gfreeau\Bundle\GetJWTBundle\Security\Firewall\GetJWTListener](https://github.com/gfreeau/GfreeauGetJWTBundle/blob/fee13315b4b99c18adf86e4cbe0525072453c59a/Security/Firewall/GetJWTListener.php#L114) blows up and cause 500 status on request payload like this one:
```json
{"username":{}}
```
or this one:
```json
{"username":true}
```
Its obviously a client error and should not generate an 500 error.

**Comment by gfreeau** [comment]
PRs are welcome if the problem persists for you. Thanks for taking the time to report it, since there has been no other activity here I'm assuming it's not affecting a lot of users. (maybe they do validation before etc)
